# SPDX-FileCopyrightText: Robert Nelson <robertcnelson@gmail.com>
# SPDX-License-Identifier: MIT
#
# You can find the Docker source files at https://openbeagle.org/beagleboard/ci-docker-images

variables:
  GIT_STRATEGY: "clone"
  GIT_DEPTH: 1
  REGISTRY_BASE: "registry.gfnd.rcn-ee.org:5000/ci"

build-arm64:
  stage: build
  image: $REGISTRY_BASE/beagle-devscripts-kernel-${DISTRO_VERSION}-arm64:latest
  tags:
    - docker-aarch64
  parallel:
    matrix:
      - DISTRO_VERSION: ["debian-12", "debian-13", "debian-14", "ubuntu-24.04"]
  script:
    - |
      if [ "$DISTRO_VERSION" = "debian-14" ]; then
        reuse lint-file src/arm/overlays/*
        reuse lint-file src/arm64/overlays/*
      fi
    - make CC=gcc CROSS_COMPILE= all
