build-debian-12-arm64:
  image: robertcnelson/beagle-devscripts-kernel-debian-12-arm64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  tags:
    - docker-aarch64
  stage: build
  script:
    - make CC=gcc CROSS_COMPILE= all

build-debian-13-arm64:
  image: robertcnelson/beagle-devscripts-kernel-debian-13-arm64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  tags:
    - docker-aarch64
  stage: build
  script:
    - make CC=gcc CROSS_COMPILE= all

build-debian-14-arm64:
  image: robertcnelson/beagle-devscripts-kernel-debian-14-arm64:latest
  # https://openbeagle.org/beagleboard/ci-docker-images
  tags:
    - docker-aarch64
  stage: build
  script:
    - reuse lint-file src/arm/overlays/*
    - reuse lint-file src/arm64/overlays/*
    - make CC=gcc CROSS_COMPILE= all
